#!/bin/bash
opkg remove asterisk-* --force-depends
echo
echo ............................. 
echo Zrobione!
echo Asterisk odinstalowany.
echo ..............................
echo Done!
echo Asterisk has been uninstalled.
echo ..............................
exit 0
